migrate(
  (app) => {
    const col = app.findCollectionByNameOrId('questions')

    const newQuestions = [
      {
        statement: 'Qual era a ideia central do modelo do Geocentrismo?',
        option_a: 'A Terra e o Sol orbitam a Lua.',
        option_b: 'A Terra estava parada no centro do universo.',
        option_c: 'O Sol estava no centro do universo.',
        option_d: 'As estrelas giravam em torno de Júpiter.',
        correct_option: 'B',
        explanation:
          'O Geocentrismo, proposto na antiguidade, afirmava que a Terra era o centro de tudo.',
        theme: 'Modelos do Universo',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Como se chama o modelo em que o Sol está no centro do sistema?',
        option_a: 'Geocentrismo',
        option_b: 'Heliocentrismo',
        option_c: 'Teocentrismo',
        option_d: 'Antropocentrismo',
        correct_option: 'B',
        explanation: 'O Heliocentrismo, consolidado por Copérnico, coloca o Sol no centro orbital.',
        theme: 'Modelos do Universo',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: "Quais são os quatro planetas 'rochosos' do nosso Sistema Solar?",
        option_a: 'Júpiter, Saturno, Urano e Netuno',
        option_b: 'Mercúrio, Vênus, Terra e Marte',
        option_c: 'Terra, Marte, Júpiter e Plutão',
        option_d: 'Sol, Lua, Terra e Marte',
        correct_option: 'B',
        explanation: 'São os planetas telúricos, mais próximos do Sol e de superfície sólida.',
        theme: 'Sistema Solar',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Qual é o maior planeta do Sistema Solar?',
        option_a: 'Saturno',
        option_b: 'Netuno',
        option_c: 'Júpiter',
        option_d: 'Terra',
        correct_option: 'C',
        explanation:
          'Júpiter é o maior planeta e é gasoso, sendo muito maior que todos os outros juntos.',
        theme: 'Sistema Solar',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'O que é a Via Láctea?',
        option_a: 'Uma constelação.',
        option_b: 'Um planeta rochoso.',
        option_c: 'A galáxia onde está localizado o Sistema Solar.',
        option_d: 'Um asteroide.',
        correct_option: 'C',
        explanation: 'A Via Láctea é a nossa galáxia espiral, contendo bilhões de estrelas.',
        theme: 'Modelos do Universo',
        difficulty: 'Média',
        suggested_grade: '7º Ano',
      },
      {
        statement: 'Como os cientistas acreditam que o Universo surgiu?',
        option_a: 'Pela Teoria do Big Bang.',
        option_b: 'A partir de uma estrela fria.',
        option_c: 'Através da fossilização.',
        option_d: 'Pelo resfriamento do gelo.',
        correct_option: 'A',
        explanation:
          'A Teoria do Big Bang sugere que o universo se originou de uma grande expansão.',
        theme: 'Origem do Universo',
        difficulty: 'Média',
        suggested_grade: '9º Ano',
      },
      {
        statement: 'Qual gás é mais abundante na atmosfera terrestre atual?',
        option_a: 'Gás carbônico',
        option_b: 'Oxigênio',
        option_c: 'Nitrogênio',
        option_d: 'Hidrogênio',
        correct_option: 'C',
        explanation: 'A atmosfera é composta por cerca de 78% de nitrogênio.',
        theme: 'Terra',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'O que caracteriza o movimento de Rotação da Terra?',
        option_a: 'A Terra gira em torno da Lua.',
        option_b: 'A Terra gira em torno do seu próprio eixo.',
        option_c: 'A Terra gira em torno do Sol.',
        option_d: 'A Terra se afasta do Sol.',
        correct_option: 'B',
        explanation:
          'Rotação é o movimento que a Terra faz em volta do seu eixo, causando dias e noites.',
        theme: 'Terra',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'O movimento de Translação é responsável por qual fenômeno?',
        option_a: 'Fases da Lua',
        option_b: 'Ciclo do nitrogênio',
        option_c: 'As estações do ano',
        option_d: 'Dias e noites',
        correct_option: 'C',
        explanation:
          'A translação em torno do Sol, junto com a inclinação do eixo, gera as estações.',
        theme: 'Terra',
        difficulty: 'Média',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Qual é o satélite natural da Terra?',
        option_a: 'Marte',
        option_b: 'Europa',
        option_c: 'Lua',
        option_d: 'Titã',
        correct_option: 'C',
        explanation: 'A Lua orbita a Terra, sendo nosso único satélite natural.',
        theme: 'Sistema Solar',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Que tipo de corpo celeste emite luz própria?',
        option_a: 'Planeta',
        option_b: 'Estrela',
        option_c: 'Satélite',
        option_d: 'Asteroide',
        correct_option: 'B',
        explanation:
          'Estrelas, como o Sol, produzem e emitem luz própria através da fusão nuclear.',
        theme: 'Universo',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Por que não podemos pisar em Júpiter?',
        option_a: 'Porque é feito de lava.',
        option_b: 'Porque ele não possui gravidade.',
        option_c: 'Porque é um planeta gasoso, sem superfície sólida.',
        option_d: 'Porque fica na outra galáxia.',
        correct_option: 'C',
        explanation:
          'Júpiter é um gigante de gás composto majoritariamente por hidrogênio e hélio.',
        theme: 'Sistema Solar',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Qual foi o primeiro modelo astronômico amplamente aceito na antiguidade?',
        option_a: 'Big Bang',
        option_b: 'Heliocêntrico',
        option_c: 'Geocêntrico',
        option_d: 'Quântico',
        correct_option: 'C',
        explanation: 'O modelo de Ptolomeu (Geocêntrico) foi aceito por muitos séculos.',
        theme: 'Modelos do Universo',
        difficulty: 'Média',
        suggested_grade: '7º Ano',
      },
      {
        statement: 'Qual fenômeno ocorre quando a Lua entra na sombra da Terra?',
        option_a: 'Eclipse Solar',
        option_b: 'Aurora Boreal',
        option_c: 'Eclipse Lunar',
        option_d: 'Maré baixa',
        correct_option: 'C',
        explanation:
          'O eclipse lunar acontece quando a Terra bloqueia a luz solar de chegar à Lua.',
        theme: 'Sistema Solar',
        difficulty: 'Média',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Qual é a teoria mais aceita sobre a formação do Sistema Solar?',
        option_a: 'Hipótese Nebular',
        option_b: 'Teoria do Big Bang',
        option_c: 'Criacionismo',
        option_d: 'Geração Espontânea',
        correct_option: 'A',
        explanation:
          'A Hipótese Nebular sugere que o sistema se formou do colapso de uma nuvem de gás e poeira.',
        theme: 'Origem da Terra',
        difficulty: 'Média',
        suggested_grade: '9º Ano',
      },
      {
        statement: 'A camada de ozônio é importante porque...',
        option_a: 'Aquece os oceanos.',
        option_b: 'Produz oxigênio respirável.',
        option_c: 'Protege contra raios ultravioleta.',
        option_d: 'Evita chuvas fortes.',
        correct_option: 'C',
        explanation: 'O ozônio filtra grande parte da radiação UV nociva vinda do Sol.',
        theme: 'Terra',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'O que é um ano-luz?',
        option_a: 'A quantidade de luz que o Sol emite em um ano.',
        option_b: 'Uma medida de distância no espaço.',
        option_c: 'O tempo que a Terra leva para orbitar o Sol.',
        option_d: 'Um tipo de calendário antigo.',
        correct_option: 'B',
        explanation: 'Ano-luz mede a distância que a luz viaja no vácuo em um ano terrestre.',
        theme: 'Universo',
        difficulty: 'Média',
        suggested_grade: '9º Ano',
      },
      {
        statement: 'Planetas que possuem anéis visíveis em nosso sistema:',
        option_a: 'Apenas Saturno',
        option_b: 'Marte, Vênus e Terra',
        option_c: 'Júpiter, Saturno, Urano e Netuno',
        option_d: 'Plutão e Mercúrio',
        correct_option: 'C',
        explanation: 'Todos os gigantes gasosos do Sistema Solar possuem algum sistema de anéis.',
        theme: 'Sistema Solar',
        difficulty: 'Média',
        suggested_grade: '7º Ano',
      },
      {
        statement: "Como se chama a 'esfera de vida' do nosso planeta?",
        option_a: 'Atmosfera',
        option_b: 'Litosfera',
        option_c: 'Biosfera',
        option_d: 'Hidrosfera',
        correct_option: 'C',
        explanation: 'A biosfera engloba todos os ecossistemas e seres vivos.',
        theme: 'Terra',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Por que a Lua tem tantas crateras visíveis?',
        option_a: 'Ela não possui atmosfera para protegê-la de meteoros.',
        option_b: 'São restos de vulcões ativos.',
        option_c: 'Os oceanos secaram.',
        option_d: 'Por causa dos ventos solares.',
        correct_option: 'A',
        explanation: 'Sem atmosfera, meteoros atingem o solo intactos.',
        theme: 'Sistema Solar',
        difficulty: 'Média',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'O que são constelações?',
        option_a: 'Agrupamentos aparentes de estrelas no céu.',
        option_b: 'Nuvens de poeira cósmica.',
        option_c: 'Sistemas de planetas.',
        option_d: 'Galáxias espirais pequenas.',
        correct_option: 'A',
        explanation: 'As constelações são padrões formados por estrelas vistas da Terra.',
        theme: 'Universo',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Qual é a temperatura média da superfície do Sol?',
        option_a: 'Cerca de 100 ºC',
        option_b: 'Cerca de 1.000 ºC',
        option_c: 'Cerca de 5.500 ºC',
        option_d: 'Milhões de graus Celsius',
        correct_option: 'C',
        explanation:
          'A superfície do Sol atinge em torno de 5.500 ºC (seu núcleo é na casa dos milhões).',
        theme: 'Sistema Solar',
        difficulty: 'Média',
        suggested_grade: '8º Ano',
      },
      {
        statement: 'As fases da Lua mudam a cada:',
        option_a: 'Semana (aproximadamente)',
        option_b: 'Mês (aproximadamente)',
        option_c: 'Ano',
        option_d: 'Dia',
        correct_option: 'A',
        explanation:
          'O ciclo completo leva cerca de 29 dias, com as quatro principais durando cerca de uma semana cada.',
        theme: 'Sistema Solar',
        difficulty: 'Fácil',
        suggested_grade: '6º Ano',
      },
      {
        statement: 'Qual cientista desenvolveu o telescópio para observar as luas de Júpiter?',
        option_a: 'Isaac Newton',
        option_b: 'Galileu Galilei',
        option_c: 'Albert Einstein',
        option_d: 'Johannes Kepler',
        correct_option: 'B',
        explanation:
          'Galileu melhorou o telescópio e fez observações cruciais que apoiaram o Heliocentrismo.',
        theme: 'Modelos do Universo',
        difficulty: 'Média',
        suggested_grade: '7º Ano',
      },
      {
        statement: 'A órbita dos planetas em torno do Sol tem formato:',
        option_a: 'Quadrado',
        option_b: 'Perfeitamente circular',
        option_c: 'Elíptico',
        option_d: 'Reto',
        correct_option: 'C',
        explanation: 'De acordo com a Primeira Lei de Kepler, as órbitas são elipses.',
        theme: 'Sistema Solar',
        difficulty: 'Média',
        suggested_grade: '8º Ano',
      },
      {
        statement: 'Em que estado físico se encontra o núcleo interno da Terra?',
        option_a: 'Gasoso',
        option_b: 'Líquido',
        option_c: 'Sólido',
        option_d: 'Plasma',
        correct_option: 'C',
        explanation: 'Apesar do imenso calor, a pressão altíssima mantém o núcleo interno sólido.',
        theme: 'Origem da Terra',
        difficulty: 'Difícil',
        suggested_grade: '9º Ano',
      },
      {
        statement: 'Qual é a principal composição do nosso Sol?',
        option_a: 'Ferro e Níquel',
        option_b: 'Oxigênio e Carbono',
        option_c: 'Hidrogênio e Hélio',
        option_d: 'Ouro e Prata',
        correct_option: 'C',
        explanation: 'O Sol é formado principalmente por hidrogênio e hélio em estado de plasma.',
        theme: 'Sistema Solar',
        difficulty: 'Média',
        suggested_grade: '7º Ano',
      },
      {
        statement: 'Por que plutão deixou de ser considerado um planeta principal?',
        option_a: 'Porque explodiu.',
        option_b: 'Não limpou a vizinhança de sua órbita.',
        option_c: 'Ele escapou do Sistema Solar.',
        option_d: 'Ele caiu no Sol.',
        correct_option: 'B',
        explanation:
          'A União Astronômica Internacional reclassificou Plutão como planeta anão por não ser dominante em sua órbita.',
        theme: 'Sistema Solar',
        difficulty: 'Difícil',
        suggested_grade: '8º Ano',
      },
      {
        statement: 'Qual destes gases é um dos principais responsáveis pelo efeito estufa?',
        option_a: 'Nitrogênio',
        option_b: 'Dióxido de carbono (CO2)',
        option_c: 'Hélio',
        option_d: 'Argônio',
        correct_option: 'B',
        explanation:
          'O CO2 retém calor na atmosfera, contribuindo intensamente para o efeito estufa.',
        theme: 'Clima',
        difficulty: 'Média',
        suggested_grade: '7º Ano',
      },
      {
        statement: 'Por que as regiões Sul/Sudeste do Brasil têm estações mais demarcadas?',
        option_a: 'Estão muito próximas da Linha do Equador.',
        option_b: 'Estão mais distantes da Linha do Equador.',
        option_c: 'Possuem menos montanhas.',
        option_d: 'A Lua afeta mais essas regiões.',
        correct_option: 'B',
        explanation:
          'Por estarem em maiores latitudes, a variação da incidência solar ao longo do ano é mais perceptível, demarcando bem as estações.',
        theme: 'Clima no Brasil',
        difficulty: 'Média',
        suggested_grade: '7º Ano',
      },
    ]

    for (const q of newQuestions) {
      try {
        app.findFirstRecordByData('questions', 'statement', q.statement)
      } catch (_) {
        const record = new Record(col)
        Object.keys(q).forEach((k) => record.set(k, q[k]))
        app.save(record)
      }
    }
  },
  (app) => {
    // best effort revert is not strictly needed for this scale
  },
)
