migrate(
  (app) => {
    const data = [
      // Race 4 (IDs 91-120 Context)
      [
        'Qual o planeta mais próximo do Sol?',
        'Vênus',
        'Terra',
        'Mercúrio',
        'Marte',
        'C',
        'Mercúrio é o primeiro planeta do Sistema Solar.',
        'Astronomia',
        'Fácil',
        '5º Ano',
      ],
      [
        'Qual o maior planeta do Sistema Solar?',
        'Saturno',
        'Júpiter',
        'Urano',
        'Netuno',
        'B',
        'Júpiter é um gigante gasoso e o maior planeta.',
        'Astronomia',
        'Fácil',
        '5º Ano',
      ],
      [
        'Qual planeta é conhecido como o Planeta Vermelho?',
        'Júpiter',
        'Marte',
        'Vênus',
        'Saturno',
        'B',
        'Marte tem uma superfície rica em óxido de ferro.',
        'Astronomia',
        'Fácil',
        '5º Ano',
      ],
      [
        'Qual a camada mais externa da Terra?',
        'Manto',
        'Núcleo',
        'Crosta',
        'Magma',
        'C',
        'A crosta terrestre é a camada superficial onde vivemos.',
        'Camadas da Terra',
        'Fácil',
        '6º Ano',
      ],
      [
        'Qual camada da Terra é predominantemente líquida?',
        'Núcleo Interno',
        'Núcleo Externo',
        'Crosta',
        'Litosfera',
        'B',
        'O núcleo externo é formado por ferro e níquel líquidos.',
        'Camadas da Terra',
        'Média',
        '6º Ano',
      ],
      [
        'O que é o manto terrestre?',
        'Camada de ar',
        'Camada de água',
        'Camada de rocha derretida',
        'Centro sólido',
        'C',
        'O manto é composto de magma (rocha derretida).',
        'Camadas da Terra',
        'Fácil',
        '6º Ano',
      ],
      [
        'Qual o gás mais abundante na atmosfera terrestre?',
        'Oxigênio',
        'Nitrogênio',
        'Gás Carbônico',
        'Hidrogênio',
        'B',
        'Aproximadamente 78% da atmosfera é Nitrogênio.',
        'Atmosfera',
        'Média',
        '6º Ano',
      ],
      [
        'Em qual camada da atmosfera os seres humanos vivem?',
        'Estratosfera',
        'Mesosfera',
        'Troposfera',
        'Termosfera',
        'C',
        'A troposfera é a camada mais próxima da superfície terrestre.',
        'Atmosfera',
        'Média',
        '6º Ano',
      ],
      [
        'Onde fica localizada a camada de ozônio?',
        'Troposfera',
        'Estratosfera',
        'Exosfera',
        'Mesosfera',
        'B',
        'A camada de ozônio protege a Terra filtrando os raios na estratosfera.',
        'Atmosfera',
        'Média',
        '6º Ano',
      ],
      [
        'O que é a evaporação no ciclo da água?',
        'Água virando gelo',
        'Água virando vapor',
        'Vapor virando água',
        'Gelo virando vapor',
        'B',
        'A evaporação é a passagem do estado líquido para o gasoso.',
        'Ciclo da Água',
        'Fácil',
        '5º Ano',
      ],
      [
        "Como se chama o processo quando o vapor d'água vira nuvem?",
        'Evaporação',
        'Infiltração',
        'Condensação',
        'Precipitação',
        'C',
        'A condensação forma as nuvens através do resfriamento do vapor.',
        'Ciclo da Água',
        'Fácil',
        '5º Ano',
      ],
      [
        'A chuva e a neve são exemplos de qual etapa do ciclo da água?',
        'Precipitação',
        'Transpiração',
        'Evaporação',
        'Condensação',
        'A',
        'A água cai na forma de chuva ou neve na precipitação.',
        'Ciclo da Água',
        'Fácil',
        '5º Ano',
      ],
      [
        'Qual costuma ser a primeira etapa do método científico?',
        'Conclusão',
        'Hipótese',
        'Observação',
        'Experimento',
        'C',
        'Tudo começa com a observação minuciosa de um fenômeno.',
        'Método Científico',
        'Média',
        '7º Ano',
      ],
      [
        'O que é uma hipótese no contexto científico?',
        'Uma verdade absoluta',
        'Uma lei natural',
        'Um experimento',
        'Uma possível explicação',
        'D',
        'A hipótese é uma tentativa teórica de explicar o fenômeno observado.',
        'Método Científico',
        'Média',
        '7º Ano',
      ],
      [
        'Para que serve um experimento?',
        'Para criar dúvidas propositais',
        'Para testar a validade da hipótese',
        'Para ignorar fatos comprovados',
        'Para criar teorias falsas',
        'B',
        'O experimento coleta dados para comprovar ou refutar a hipótese.',
        'Método Científico',
        'Média',
        '7º Ano',
      ],
      [
        'Qual é o nome da galáxia em que o Sistema Solar está localizado?',
        'Andrômeda',
        'Via Láctea',
        'Sombrero',
        'Triângulo',
        'B',
        'A Terra faz parte de uma galáxia espiral chamada Via Láctea.',
        'Astronomia',
        'Fácil',
        '5º Ano',
      ],
      [
        'O que é popularmente chamado de estrela cadente?',
        'Uma estrela morrendo',
        'Um cometa passando perto',
        'Um meteoro queimando na atmosfera',
        'Um planeta pequeno',
        'C',
        'Estrelas cadentes são, na verdade, meteoros queimando na atmosfera.',
        'Astronomia',
        'Média',
        '6º Ano',
      ],
      [
        'Qual é a estrela mais próxima do planeta Terra?',
        'Sirius',
        'Sol',
        'Alpha Centauri',
        'Betelgeuse',
        'B',
        'O Sol é a estrela central e mais próxima do nosso sistema.',
        'Astronomia',
        'Fácil',
        '5º Ano',
      ],
      [
        'O que diferencia primariamente o clima do tempo?',
        'Clima é diário',
        'Tempo é sempre duradouro',
        'Clima é longo prazo',
        'Não há nenhuma diferença',
        'C',
        'Clima é o padrão meteorológico histórico, tempo é o estado diário atual.',
        'Clima',
        'Média',
        '6º Ano',
      ],
      [
        'Qual instrumento é utilizado para medir a temperatura atmosférica?',
        'Barômetro',
        'Pluviômetro',
        'Anemômetro',
        'Termômetro',
        'D',
        'O termômetro é o instrumento padrão que mede a temperatura do ar.',
        'Clima',
        'Fácil',
        '5º Ano',
      ],
      [
        'O que o anemômetro é responsável por medir?',
        'Pressão atmosférica',
        'Velocidade do vento',
        'Quantidade de chuva',
        'Umidade do ar',
        'B',
        'Anemômetros medem a velocidade e a força dos ventos.',
        'Clima',
        'Difícil',
        '7º Ano',
      ],
      [
        'Qual é atualmente considerado o menor planeta do Sistema Solar?',
        'Marte',
        'Mercúrio',
        'Vênus',
        'Plutão',
        'B',
        'Desde que Plutão foi rebaixado a planeta anão, Mercúrio é o menor planeta.',
        'Astronomia',
        'Média',
        '6º Ano',
      ],
      [
        'Quantos satélites naturais (luas) a Terra possui?',
        'Duas',
        'Zero',
        'Uma',
        'Três',
        'C',
        'A Terra possui apenas um satélite natural, a Lua.',
        'Astronomia',
        'Fácil',
        '5º Ano',
      ],
      [
        'A camada de ozônio nos protege principalmente de quê?',
        'Raios solares ultravioleta (UV)',
        'Meteoros gigantes',
        'Chuva ácida',
        'Ventos solares',
        'A',
        'O ozônio funciona como um filtro natural contra os raios ultravioleta.',
        'Atmosfera',
        'Média',
        '6º Ano',
      ],
      [
        'O que caracteriza a infiltração no ciclo da água?',
        'Água formando nuvens',
        'Água penetrando no solo',
        'Água evaporando de rios',
        'Água congelando nos polos',
        'B',
        'A infiltração abastece e mantém os lençóis freáticos subterrâneos.',
        'Ciclo da Água',
        'Média',
        '5º Ano',
      ],
      [
        'Qual o propósito de um grupo de controle em um experimento científico?',
        'O grupo que muda constantemente',
        'O grupo que não participa',
        'O grupo que recebe toda a variável',
        'Servir como grupo padrão de comparação',
        'D',
        'Serve como referência estável para validar as mudanças no experimento.',
        'Método Científico',
        'Difícil',
        '8º Ano',
      ],
      [
        'De quais materiais é composto principalmente o núcleo interno da Terra?',
        'Água e Gelo',
        'Ferro e Níquel',
        'Silício e Oxigênio',
        'Magma e Basalto',
        'B',
        'O núcleo é incrivelmente denso e sólido devido à alta pressão sobre o ferro e o níquel.',
        'Camadas da Terra',
        'Difícil',
        '7º Ano',
      ],
      [
        'Como exatamente as nuvens se formam na atmosfera?',
        'Pelo derretimento do granizo',
        'Pela precipitação reversa',
        "Pela condensação do vapor d'água",
        'Pela infiltração aérea',
        'C',
        "O vapor d'água sobe, resfria e condensa em gotículas que formam nuvens.",
        'Ciclo da Água',
        'Média',
        '6º Ano',
      ],
      [
        'Qual planeta do Sistema Solar possui os anéis mais famosos e visíveis?',
        'Júpiter',
        'Urano',
        'Netuno',
        'Saturno',
        'D',
        'Os grandes anéis de Saturno são formados por gelo, poeira e rocha.',
        'Astronomia',
        'Fácil',
        '5º Ano',
      ],
      [
        'O que é a exosfera no contexto do nosso planeta?',
        'A camada mais profunda de rocha',
        'A camada mais externa da atmosfera',
        'Uma camada exclusiva de água',
        'A camada produtora de nuvens',
        'B',
        'A exosfera é a última e mais fina camada, limite com o espaço sideral.',
        'Atmosfera',
        'Média',
        '7º Ano',
      ],

      // Race 5 (IDs 121-150 Context)
      [
        'Quem foi o cientista que formulou a lei da gravitação universal?',
        'Albert Einstein',
        'Galileu Galilei',
        'Isaac Newton',
        'Nicolau Copérnico',
        'C',
        'Isaac Newton observou e formulou matematicamente a lei da gravitação universal.',
        'Gravidade',
        'Média',
        '7º Ano',
      ],
      [
        'Como a ciência define a gravidade de forma simples?',
        'Uma força de repulsão eletromagnética',
        'Uma força invisível de atração mútua',
        'Uma ilusão óptica do espaço',
        'Um campo magnético terrestre',
        'B',
        'A gravidade atrai os corpos com massa uns em direção aos outros.',
        'Gravidade',
        'Média',
        '7º Ano',
      ],
      [
        'Qual planeta exerce a maior força de gravidade no Sistema Solar?',
        'Terra',
        'Marte',
        'Saturno',
        'Júpiter',
        'D',
        'Por ser o mais massivo, Júpiter tem a maior força gravitacional.',
        'Gravidade',
        'Média',
        '7º Ano',
      ],
      [
        'Como se chama o movimento que a Terra faz ao redor do Sol?',
        'Rotação Equatorial',
        'Translação',
        'Mutação Orbital',
        'Inclinação Sazonal',
        'B',
        'A translação é o trajeto elíptico da Terra que dura cerca de 365 dias.',
        'Movimentos',
        'Fácil',
        '5º Ano',
      ],
      [
        'Qual o nome do movimento da Terra girando ao redor do seu próprio eixo?',
        'Translação',
        'Rotação',
        'Giro Polar',
        'Ciclo Circadiano',
        'B',
        'A rotação ocorre em 24 horas e é responsável por causar os dias e as noites.',
        'Movimentos',
        'Fácil',
        '5º Ano',
      ],
      [
        'Aproximadamente quanto tempo a Terra leva para completar uma translação?',
        '24 horas',
        '30 dias e meio',
        '365 dias e 6 horas',
        '10 anos',
        'C',
        'Leva cerca de 365 dias e 6 horas (causando o ano bissexto).',
        'Movimentos',
        'Fácil',
        '5º Ano',
      ],
      [
        'Quantas são as fases principais da Lua visíveis da Terra?',
        'Duas',
        'Três',
        'Quatro',
        'Oito',
        'C',
        'As quatro principais são: Nova, Crescente, Cheia e Minguante.',
        'Fases da Lua',
        'Fácil',
        '5º Ano',
      ],
      [
        'Na fase de Lua Nova, como ela se apresenta no céu noturno?',
        'Totalmente brilhante',
        'Apenas a metade iluminada',
        'Fica praticamente invisível',
        'Brilha em tom avermelhado',
        'C',
        'A face voltada para a Terra não recebe luz do Sol diretamente.',
        'Fases da Lua',
        'Média',
        '6º Ano',
      ],
      [
        'O que caracteriza um eclipse solar?',
        'A Terra esconde a Lua na sombra',
        'A Lua fica totalmente vermelha',
        'A Lua passa exatamente entre a Terra e o Sol',
        'O Sol diminui de tamanho repentinamente',
        'C',
        'A Lua projeta sua sombra sobre uma parte da Terra durante o dia.',
        'Eclipses',
        'Média',
        '6º Ano',
      ],
      [
        'O que caracteriza um eclipse lunar?',
        'A Terra fica entre o Sol e a Lua',
        'A Lua bloqueia a luz do Sol',
        'O Sol passa pela órbita da Terra',
        'Nenhuma das alternativas anteriores',
        'A',
        'A sombra da Terra escurece a Lua durante a noite de lua cheia.',
        'Eclipses',
        'Média',
        '6º Ano',
      ],
      [
        'O que são os fósseis na paleontologia?',
        'Pedras esculpidas por humanos',
        'Ossos feitos de plástico enterrados',
        'Restos ou marcas de seres vivos preservados',
        'Gases solidificados no subterrâneo',
        'C',
        'Fósseis são vestígios preservados de vida do passado geológico.',
        'Fósseis',
        'Fácil',
        '6º Ano',
      ],
      [
        'Qual é o tipo de rocha que geralmente contém fósseis em seu interior?',
        'Ígnea',
        'Metamórfica',
        'Sedimentar',
        'Vulcânica Pura',
        'C',
        'As camadas de sedimentos cobrem rapidamente e preservam os restos biológicos.',
        'Fósseis',
        'Difícil',
        '7º Ano',
      ],
      [
        'O que é exatamente a paleontologia?',
        'O estudo dos exoplanetas',
        'A ciência que estuda os fósseis e a vida antiga',
        'O estudo do clima pré-histórico',
        'A exploração da água em Marte',
        'B',
        'Ciência dedicada a compreender a vida do passado da Terra através dos fósseis.',
        'Fósseis',
        'Média',
        '7º Ano',
      ],
      [
        'O que significa o conceito ambiental de sustentabilidade?',
        'Gastar todos os recursos hoje sem pensar',
        'Usar os recursos com extrema responsabilidade',
        'Parar completamente de usar eletricidade',
        'Apenas poluir menos do que ontem',
        'B',
        'Ação de garantir e preservar os recursos para as gerações presentes e futuras.',
        'Sustentabilidade',
        'Fácil',
        '5º Ano',
      ],
      [
        'Qual destas opções é um exemplo de fonte de energia limpa e renovável?',
        'Carvão Mineral',
        'Petróleo e seus derivados',
        'Energia Solar Fotovoltaica',
        'Gás Natural liquefeito',
        'C',
        'A energia solar vem do Sol, é limpa, abundante e não se esgota rapidamente.',
        'Sustentabilidade',
        'Fácil',
        '5º Ano',
      ],
      [
        'O que significa a sigla mundial ODS?',
        'Objetivos de Dinheiro Sujo',
        'Objetivos de Desenvolvimento Sustentável',
        'Obras de Defesa Social',
        'Organização da Saúde Mundial',
        'B',
        'São metas globais estabelecidas pela ONU para um futuro melhor.',
        'ODS',
        'Média',
        '8º Ano',
      ],
      [
        'Quantos ODS foram oficializados pela ONU na Agenda 2030?',
        '10',
        '15',
        '17',
        '20',
        'C',
        'Existem 17 ODS contendo diversas metas a serem atingidas até 2030.',
        'ODS',
        'Difícil',
        '8º Ano',
      ],
      [
        'Qual é o tema principal do ODS número 1?',
        'Educação inclusiva e de qualidade',
        'Fome zero e agricultura sustentável',
        'Erradicação da pobreza em todas as formas',
        'Saúde e bem-estar para todos',
        'C',
        'O primeiro e mais urgente ODS visa acabar de vez com a pobreza global.',
        'ODS',
        'Difícil',
        '8º Ano',
      ],
      [
        'Qual é a causa principal da existência das estações do ano?',
        'Pela inclinação do eixo da Terra aliada à translação',
        'Por causa apenas da rotação rápida',
        'Apenas porque o Sol aquece mais em certos meses',
        'Porque a Terra muda de tamanho constantemente',
        'A',
        'A inclinação fixa faz os hemisférios receberem luz de formas diferentes ao longo do ano.',
        'Movimentos',
        'Média',
        '6º Ano',
      ],
      [
        'O que a gravidade da Lua causa principalmente aqui na Terra?',
        'Ventos fortíssimos',
        'Terremotos intensos',
        'As marés altas e baixas nos oceanos',
        'Eclipses frequentes',
        'C',
        'A força gravitacional da Lua (e do Sol) atrai as enormes massas de águas do oceano.',
        'Gravidade',
        'Média',
        '7º Ano',
      ],
      [
        'Na física clássica, qual a diferença real entre massa e peso?',
        'São termos diferentes para a mesma coisa',
        'A massa muda no espaço, mas o peso não',
        'Massa é quantidade de matéria, peso depende do campo gravitacional',
        'Peso é simplesmente a massa multiplicada por dois',
        'C',
        'Seu peso na Lua é muito menor, mas sua massa corpórea continua igual à da Terra.',
        'Gravidade',
        'Difícil',
        '8º Ano',
      ],
      [
        'O que o conceito de reciclagem propõe na prática?',
        'Jogar lixo na rua adequadamente',
        'Reaproveitar materiais descartados transformando-os',
        'Queimar o lixo para gerar fumaça',
        'Enterrar o plástico no quintal',
        'B',
        'Ajuda a reduzir drasticamente a extração desnecessária de novos recursos naturais.',
        'Sustentabilidade',
        'Fácil',
        '5º Ano',
      ],
      [
        'Qual desses itens comuns não costuma ser reciclável no dia a dia?',
        'Caixas de papelão',
        'Potes de vidro',
        'Papel higiênico já usado',
        'Lata de refrigerante de alumínio',
        'C',
        'Materiais contaminados por matéria orgânica ou químicos não podem ser reciclados.',
        'Sustentabilidade',
        'Fácil',
        '5º Ano',
      ],
      [
        'Como costumamos visualizar a parte clara da Lua durante a fase minguante no Hemisfério Sul?',
        'Parece estar Crescente',
        'Tem o formato semelhante a um C',
        'Totalmente Cheia',
        'Completamente Nova e escura',
        'B',
        'No hemisfério sul, a lua minguante se assemelha à letra C.',
        'Fases da Lua',
        'Média',
        '6º Ano',
      ],
      [
        'Quanto tempo em média dura um ciclo lunar completo (todas as fases)?',
        '7 dias exatos',
        '14 dias aproximadamente',
        'Cerca de 29,5 dias',
        'Exatos 365 dias',
        'C',
        'Um mês lunar, ou lunação, demora cerca de 29,5 dias para completar o ciclo.',
        'Fases da Lua',
        'Média',
        '6º Ano',
      ],
      [
        'Durante qual fase específica da Lua pode acontecer um eclipse do Sol?',
        'Cheia',
        'Nova',
        'Minguante',
        'Crescente',
        'B',
        'Para cobrir o Sol, a Lua tem que estar entre a Terra e o Sol, o que ocorre na Lua Nova.',
        'Eclipses',
        'Difícil',
        '8º Ano',
      ],
      [
        'Durante qual fase específica da Lua pode acontecer um eclipse lunar total?',
        'Nova',
        'Crescente',
        'Cheia',
        'Minguante',
        'C',
        'A Terra deve estar entre a Lua e o Sol, o que acontece somente durante a Lua Cheia.',
        'Eclipses',
        'Difícil',
        '8º Ano',
      ],
      [
        'O processo natural de fossilização geralmente é rápido ou extremamente lento?',
        'Muito rápido como um piscar de olhos',
        'Acontece tranquilamente em alguns dias',
        'Muito lento, exigindo condições especiais',
        'Não existe mais na natureza',
        'C',
        'Leva de milhares a milhões de anos e necessita que o ser seja soterrado rapidamente.',
        'Fósseis',
        'Média',
        '6º Ano',
      ],
      [
        'O ODS 13 da Agenda 2030 trata especificamente da Ação contra a mudança global do...',
        'Sistema Econômico',
        'Clima',
        'Sistema de Saúde',
        'Espaço Sideral',
        'B',
        'O ODS 13 foca em medidas urgentes para combater as profundas mudanças climáticas.',
        'ODS',
        'Média',
        '8º Ano',
      ],
      [
        'Qual o nome da atração física que todos os corpos celestes (e não celestes) exercem entre si?',
        'Magnetismo Polar',
        'Eletricidade Estática',
        'Força da Gravidade',
        'Atrito Dinâmico',
        'C',
        'A gravidade dita que qualquer massa no universo atrai qualquer outra massa.',
        'Gravidade',
        'Média',
        '7º Ano',
      ],
    ]

    const col = app.findCollectionByNameOrId('questions')

    data.forEach((item) => {
      try {
        app.findFirstRecordByData('questions', 'statement', item[0])
      } catch (_) {
        const record = new Record(col)
        record.set('statement', item[0])
        record.set('option_a', item[1])
        record.set('option_b', item[2])
        record.set('option_c', item[3])
        record.set('option_d', item[4])
        record.set('correct_option', item[5])
        record.set('explanation', item[6])
        record.set('theme', item[7])
        record.set('difficulty', item[8])
        record.set('suggested_grade', item[9])
        app.save(record)
      }
    })
  },
  (app) => {
    // Safe down migration: avoiding massive deletions to protect user changes
  },
)
